// Styles
const styles: { [key: string]: React.CSSProperties } = {
  pageContainer: {
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Oxygen, Ubuntu, Cantarell, sans-serif',
    background: 'linear-gradient(135deg, #adb9f2 0%, #f8f8f8 100%)',
    minHeight: '100vh',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '20px',
  },
  container: {
    width: '100%',
    maxWidth: '900px',
    height: '90vh',
    maxHeight: '800px',
    background: 'white',
    borderRadius: '12px',
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.3)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  header: {
    background: 'linear-gradient(135deg, #667eea 0%, #5060db 100%)',
    color: 'white',
    padding: '20px',
    borderBottom: '1px solid rgba(0, 0, 0, 0.1)',
  },
  headerTitle: {
    fontSize: '24px',
    marginBottom: '12px',
    margin: 0,
  },
  configSection: {
    display: 'flex',
    gap: '10px',
    alignItems: 'center',
    flexWrap: 'wrap',
  },
  configLabel: {
    fontSize: '13px',
    opacity: 0.9,
  },
  configInput: {
    padding: '6px 10px',
    border: '1px solid rgba(255, 255, 255, 0.3)',
    borderRadius: '4px',
    fontSize: '12px',
    width: '300px',
    background: 'rgba(255, 255, 255, 0.2)',
    color: 'white',
  },
  configButton: {
    padding: '6px 12px',
    background: 'rgba(255, 255, 255, 0.2)',
    color: 'white',
    border: '1px solid rgba(255, 255, 255, 0.3)',
    borderRadius: '4px',
    cursor: 'pointer',
    fontSize: '12px',
    transition: 'all 0.2s',
  },
  messages: {
    flex: 1,
    overflowY: 'auto',
    padding: '20px',
    background: '#f8f9fa',
    display: 'flex',
    flexDirection: 'column',
    gap: '12px',
  },
  message: {
    display: 'flex',
    gap: '8px',
    animation: 'slideIn 0.3s ease-out',
    alignItems: 'flex-end',
  },
  messageUser: {
    justifyContent: 'flex-end',
  },
  messageContent: {
    maxWidth: '70%',
    padding: '12px 16px',
    borderRadius: '12px',
    wordWrap: 'break-word',
    lineHeight: '1.4',
    fontSize: '14px',
  },
  messageContentUser: {
    background: 'linear-gradient(135deg, #76cba5 0%, #b9e7d4 100%)',
    color: 'white',
    borderBottomRightRadius: '4px',
  },
  messageContentAi: {
    background: '#e9ecef',
    color: '#222',
    borderBottomLeftRadius: '4px',
  },
  messageContentSystem: {
    background: '#e0f2fe',
    color: '#0c4a6e',
    borderBottomLeftRadius: '4px',
    fontSize: '12px',
  },
  messageContentUi: {
    background: '#f1f5f9',
    color: '#334155',
    borderBottomLeftRadius: '4px',
    fontSize: '12px',
    alignSelf: 'center',
    maxWidth: '90%',
    textAlign: 'center',
  },
  messageContentError: {
    background: '#fff3cd',
    color: '#856404',
    borderBottomLeftRadius: '4px',
    fontSize: '12px',
    alignSelf: 'center',
    maxWidth: '90%',
    textAlign: 'center',
  },
  speakControls: {
    display: 'flex',
    gap: '6px',
    alignSelf: 'flex-end',
  },
  speakButton: {
    width: '32px',
    height: '32px',
    borderRadius: '50%',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: '#d0d7de',
    background: 'white',
    color: '#4b5563',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    cursor: 'pointer',
    padding: 0,
    lineHeight: 1,
  },
  speakButtonPause: {
    color: '#9333ea',
    borderColor: '#e9d5ff',
  },
  speakButtonDim: {
    opacity: 0.6,
  },
  speakButtonActive: {
    boxShadow: '0 0 0 3px rgba(147, 51, 234, 0.2)',
  },
  inputSection: {
    padding: '20px',
    background: 'white',
    borderTop: '1px solid #e0e0e0',
    display: 'flex',
    gap: '10px',
  },
  inputWrapper: {
    flex: 1,
    display: 'flex',
    gap: '8px',
  },
  messageInput: {
    flex: 1,
    padding: '12px 16px',
    border: '1px solid #ddd',
    borderRadius: '8px',
    fontSize: '14px',
    fontFamily: 'inherit',
    resize: 'none',
    maxHeight: '100px',
    transition: 'all 0.2s',
  },
  sendButton: {
    padding: '12px 24px',
    background: 'linear-gradient(135deg, #667eea 0%, #5163b3 100%)',
    color: 'white',
    border: 'none',
    borderRadius: '8px',
    cursor: 'pointer',
    fontWeight: 600,
    transition: 'all 0.2s',
    whiteSpace: 'nowrap',
  },
  clearButton: {
    padding: '12px 16px',
    background: '#f0f0f0',
    color: '#333',
    border: '1px solid #ddd',
    borderRadius: '8px',
    cursor: 'pointer',
    transition: 'all 0.2s',
  },
  status: {
    fontSize: '12px',
    color: '#666',
    padding: '0 16px',
    marginTop: '8px',
  },
  statusError: {
    background: '#f8d7da',
    color: '#721c24',
    padding: '12px 16px',
    borderRadius: '8px',
    marginBottom: '8px',
    borderLeft: '4px solid #f5c6cb',
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
    padding: '20px',
  },
  modalContent: {
    backgroundColor: 'white',
    borderRadius: '12px',
    maxWidth: '800px',
    width: '100%',
    maxHeight: '90vh',
    boxShadow: '0 20px 60px rgba(0, 0, 0, 0.3)',
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
  },
  modalHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: '20px',
    borderBottom: '1px solid #e0e0e0',
    background: 'linear-gradient(135deg, #667eea 0%, #5060db 100%)',
  },
  modalTitle: {
    margin: 0,
    fontSize: '20px',
    fontWeight: 600,
    color: 'white',
  },
  modalCloseButton: {
    background: 'rgba(255, 255, 255, 0.2)',
    border: '1px solid rgba(255, 255, 255, 0.3)',
    borderRadius: '4px',
    width: '32px',
    height: '32px',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    cursor: 'pointer',
    fontSize: '20px',
    color: 'white',
    transition: 'all 0.2s',
    padding: 0,
  },
  modalBody: {
    overflowY: 'auto',
    flex: 1,
  },
};
export default styles;